# CSV file with single column, patient, with every patient ID
patients: patients.csv
# CSV file with info on each sample/read group
units: units.csv

# Sequencing Type
sequencing_type: WES

# Genomic Regions
# For WES data, coverage is evaluated based on reads in these regions
genomic_regions: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/refdata/hg38_Twist_ILMN_Exome_2.0_Plus_Panel_annotated.BED

# Reference Data Sources
# Directory of all reference data
ref_dir: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/refdata
# Name of the human reference FASTA
ref_fasta: Homo_sapiens_assembly38.fasta
# VCF files with known mutations from different sources
known_sites: dbsnp_146.hg38.vcf.gz, resources-broad-hg38-v0-Homo_sapiens_assembly38.known_indels.vcf.gz, 1000G_phase1.snps.high_confidence.hg38.vcf.gz
# AF only VCF with common allele frequencies - using gnomAD file
germline_resource: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/refdata/gnomAD/af-only-gnomad.hg38.vcf.gz
# Biallelic variants only VCF with AF data - use EXAC file
contamination_resource: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/refdata/gnomAD/small_exac_common_3.hg38.vcf.gz

# GATK TMP directory
# Alternative filepath that has larger storage (ie $SCRATCH)
tmp_dir: /data/Unit_LMM/selberherr-group/kacar/tmp/

# Mutect2 Settings
# Number of Mutect2 workers per sample
num_workers: 40
# Variant calling without matched normal
tumor_only: true
# Additional flags for Mutect2
mutect2_flags: None
# Additional flags for FilterMutectCalls
filter_flags: --min-reads-per-strand 1

# Panel of Normal (PON)
# Use PON with Mutect2 for variant calling
use_pon: true
# Filepath for PON. To create a new PON from all the normal samples, specify as None
pon_vcf: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/refdata/panel_of_normals/1000g_pon.hg38.vcf.gz


# Annotation data sources
# Directory with VEP annotation data
vep_dir: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/refdata/vep
# Assembly version name
assembly_version: GRCh38
# Value for Center field in the combined MAF
center_name: Wöhrer Lab
# Alternate Isoforms For vcf2maf Selection. Set as None to use Ensembl defaults
alternate_isoforms: None

## Singularity Containers
## This specifies the container to use for various steps in the pipeline
## The value can be any string (either local path or url) that can be queried using singularity pull
gatk_container:
multiqc_container: 
mosdepth_container:
fastqc_container:
vep_container:
eda_container: 
