# CSV file with single column, patient, includes patient ID
patients: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/workflow/patients.csv

# CSV file for individual samples from each patient, includes 4x ubam files per sample
units: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/workflow/units.csv

# Sequencing Type
sequencing_type: WES

# Genomic Regions
# For WES data, coverage is evaluated based on reads in these regions
genomic_regions: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/workflow/refdata/SureSelect-Exon_v5.S04380110.Covered.bed

# Reference Data Sources
# Directory of all reference data
ref_dir: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/resources

# Name of the human reference FASTA
ref_fasta: Homo_sapiens_assembly38.fasta

# VCF files with known mutations from different sources
known_sites: dbsnp_146.hg38.vcf.gz, resources-broad-hg38-v0-Homo_sapiens_assembly38.known_indels.vcf.gz, 1000G_phase1.snps.high_confidence.hg38.vcf.gz
# AF only VCF with common allele frequencies - using gnomAD file
germline_resource: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/resources/gnomAD/af-only-gnomad.hg38.vcf.gz
# Biallelic variants only VCF with AF data - use EXAC file
contamination_resource: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/resources/gnomAD/small_exac_common_3.hg38.vcf.gz
# GATK TMP directory
# Alternative filepath that has larger storage (ie $SCRATCH)
tmp_dir: /data/Unit_LMM/selberherr-group/kacar/tmp/

# Mutect2 Settings
# Number of Mutect2 workers per sample
num_workers: 40
# Variant calling without matched normal
tumor_only: true
# Additional flags for Mutect2
mutect2_flags: None
# Additional flags for FilterMutectCalls
filter_flags: --min-reads-per-strand 1

# Panel of Normal (PON)
# Use PON with Mutect2 for variant calling
use_pon: true
# Filepath for PON. To create a new PON from all the normal samples, specify as None
pon_vcf: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/resources/panel_of_normals/1000g_pon.hg38.vcf.gz

# Apply additional thresholds to filter variants
# When set to true, requires each SNV has a minimum of
# 15 reads covering the position and at least 5 reads
# with the mutant allele.
# When false, only use FilterMutectCalls criteria
stringent_filtering: false

# Annotation data sources
# Directory with VEP annotation data
vep_dir: /data/Unit_LMM/selberherr-group/kacar/ngs-gatk-ssv-tumoronly/refdata/vep
# Assembly version name
assembly_version: GRCh38
# Value for Center field in the combined MAF
center_name: Wöhrer Lab
# Alternate Isoforms For vcf2maf Selection. Set as None to use Ensembl defaults
alternate_isoforms: None

## Conda Env
conda_env:
